services:
  claude-cli:
    build: .
    container_name: claude-cli-container
    ports:
      - "22:22"  # Map container SSH port to host port 22
      - "5300:3000"  # React/Node.js web app port
      - "5301:3001"  # Additional web app port
      - "5302:3002"  # Additional web app port
      - "5303:3003"  # Additional web app port
      - "5304:3004"  # Additional web app port
      - "5305:3005"  # Additional web app port
      - "5800:8000"  # Python/Django port
      - "5808:8080"  # Alternative web port
      - "5500:5000"  # Flask port
    volumes:
      - ./workspace:/home/claude/workspace  # Mount workspace for persistent data
      - ./claude-config:/home/claude/.claude  # Mount Claude configuration and state
      - ./workspace/ssh-keys:/home/claude/.ssh  # Mount SSH keys from workspace
      - ./tailscale-config:/var/lib/tailscale  # Persistent Tailscale config
      - ./CLAUDE.md:/home/claude/workspace/CLAUDE.md  # Mount project memory file
      - ./CLAUDE.md:/home/claude/.claude/CLAUDE.md  # Mount project memory file to Claude config
      - ./ssh-host-keys:/etc/ssh/host-keys  # Persistent SSH host keys
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}  # Pass API key from environment
      - TS_AUTHKEY=${TS_AUTHKEY}  # Tailscale auth key
    cap_add:
      - NET_ADMIN  # Required for Tailscale
    restart: unless-stopped
    networks:
      - claude-network

networks:
  claude-network:
    driver: bridge 